//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4927.
// 
#pragma warning disable 1591

namespace NoIdeas.Client.cloudWebRef {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using NoIdeas.Phone.Lib;
    using System.Collections.Generic;
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NoIdeasWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class NoIdeasWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UpdateProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateDatingProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertNewUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadDatingProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletedatingProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback RunAndFindMatchesOperationCompleted;
        
        private System.Threading.SendOrPostCallback EndSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNumberOfActiveUsersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NoIdeasWebService() {
            this.Url = global::NoIdeas.Client.Properties.Settings.Default.NoIdeas_Client_cloudWebRef_NoIdeasWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UpdateProfileCompletedEventHandler UpdateProfileCompleted;
        
        /// <remarks/>
        public event UpdateDatingProfileCompletedEventHandler UpdateDatingProfileCompleted;
        
        /// <remarks/>
        public event InsertNewUserCompletedEventHandler InsertNewUserCompleted;
        
        /// <remarks/>
        public event GetUserProfileCompletedEventHandler GetUserProfileCompleted;
        
        /// <remarks/>
        public event LoginCheckCompletedEventHandler LoginCheckCompleted;
        
        /// <remarks/>
        public event LoadDatingProfileCompletedEventHandler LoadDatingProfileCompleted;
        
        /// <remarks/>
        public event DeletedatingProfileCompletedEventHandler DeletedatingProfileCompleted;
        
        /// <remarks/>
        public event RunAndFindMatchesCompletedEventHandler RunAndFindMatchesCompleted;
        
        /// <remarks/>
        public event EndSessionCompletedEventHandler EndSessionCompleted;
        
        /// <remarks/>
        public event GetNumberOfActiveUsersCompletedEventHandler GetNumberOfActiveUsersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateProfile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateProfile(Profile profile) {
            object[] results = this.Invoke("UpdateProfile", new object[] {
                        profile});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateProfileAsync(Profile profile) {
            this.UpdateProfileAsync(profile, null);
        }
        
        /// <remarks/>
        public void UpdateProfileAsync(Profile profile, object userState) {
            if ((this.UpdateProfileOperationCompleted == null)) {
                this.UpdateProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateProfileOperationCompleted);
            }
            this.InvokeAsync("UpdateProfile", new object[] {
                        profile}, this.UpdateProfileOperationCompleted, userState);
        }
        
        private void OnUpdateProfileOperationCompleted(object arg) {
            if ((this.UpdateProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateProfileCompleted(this, new UpdateProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateDatingProfile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateDatingProfile(DatingProfile dprofile) {
            object[] results = this.Invoke("UpdateDatingProfile", new object[] {
                        dprofile});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateDatingProfileAsync(DatingProfile dprofile) {
            this.UpdateDatingProfileAsync(dprofile, null);
        }
        
        /// <remarks/>
        public void UpdateDatingProfileAsync(DatingProfile dprofile, object userState) {
            if ((this.UpdateDatingProfileOperationCompleted == null)) {
                this.UpdateDatingProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateDatingProfileOperationCompleted);
            }
            this.InvokeAsync("UpdateDatingProfile", new object[] {
                        dprofile}, this.UpdateDatingProfileOperationCompleted, userState);
        }
        
        private void OnUpdateDatingProfileOperationCompleted(object arg) {
            if ((this.UpdateDatingProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateDatingProfileCompleted(this, new UpdateDatingProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertNewUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertNewUser(Profile profile) {
            object[] results = this.Invoke("InsertNewUser", new object[] {
                        profile});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertNewUserAsync(Profile profile) {
            this.InsertNewUserAsync(profile, null);
        }
        
        /// <remarks/>
        public void InsertNewUserAsync(Profile profile, object userState) {
            if ((this.InsertNewUserOperationCompleted == null)) {
                this.InsertNewUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertNewUserOperationCompleted);
            }
            this.InvokeAsync("InsertNewUser", new object[] {
                        profile}, this.InsertNewUserOperationCompleted, userState);
        }
        
        private void OnInsertNewUserOperationCompleted(object arg) {
            if ((this.InsertNewUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertNewUserCompleted(this, new InsertNewUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserProfile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Profile GetUserProfile(string nickName) {
            object[] results = this.Invoke("GetUserProfile", new object[] {
                        nickName});
            return ((Profile)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserProfileAsync(string nickName) {
            this.GetUserProfileAsync(nickName, null);
        }
        
        /// <remarks/>
        public void GetUserProfileAsync(string nickName, object userState) {
            if ((this.GetUserProfileOperationCompleted == null)) {
                this.GetUserProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserProfileOperationCompleted);
            }
            this.InvokeAsync("GetUserProfile", new object[] {
                        nickName}, this.GetUserProfileOperationCompleted, userState);
        }
        
        private void OnGetUserProfileOperationCompleted(object arg) {
            if ((this.GetUserProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserProfileCompleted(this, new GetUserProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoginCheck", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool LoginCheck(string nickName, string password) {
            object[] results = this.Invoke("LoginCheck", new object[] {
                        nickName,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LoginCheckAsync(string nickName, string password) {
            this.LoginCheckAsync(nickName, password, null);
        }
        
        /// <remarks/>
        public void LoginCheckAsync(string nickName, string password, object userState) {
            if ((this.LoginCheckOperationCompleted == null)) {
                this.LoginCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginCheckOperationCompleted);
            }
            this.InvokeAsync("LoginCheck", new object[] {
                        nickName,
                        password}, this.LoginCheckOperationCompleted, userState);
        }
        
        private void OnLoginCheckOperationCompleted(object arg) {
            if ((this.LoginCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCheckCompleted(this, new LoginCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadDatingProfile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool LoadDatingProfile(DatingProfile dprofile) {
            object[] results = this.Invoke("LoadDatingProfile", new object[] {
                        dprofile});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LoadDatingProfileAsync(DatingProfile dprofile) {
            this.LoadDatingProfileAsync(dprofile, null);
        }
        
        /// <remarks/>
        public void LoadDatingProfileAsync(DatingProfile dprofile, object userState) {
            if ((this.LoadDatingProfileOperationCompleted == null)) {
                this.LoadDatingProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadDatingProfileOperationCompleted);
            }
            this.InvokeAsync("LoadDatingProfile", new object[] {
                        dprofile}, this.LoadDatingProfileOperationCompleted, userState);
        }
        
        private void OnLoadDatingProfileOperationCompleted(object arg) {
            if ((this.LoadDatingProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadDatingProfileCompleted(this, new LoadDatingProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeletedatingProfile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeletedatingProfile(DatingProfile dprofile) {
            object[] results = this.Invoke("DeletedatingProfile", new object[] {
                        dprofile});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeletedatingProfileAsync(DatingProfile dprofile) {
            this.DeletedatingProfileAsync(dprofile, null);
        }
        
        /// <remarks/>
        public void DeletedatingProfileAsync(DatingProfile dprofile, object userState) {
            if ((this.DeletedatingProfileOperationCompleted == null)) {
                this.DeletedatingProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletedatingProfileOperationCompleted);
            }
            this.InvokeAsync("DeletedatingProfile", new object[] {
                        dprofile}, this.DeletedatingProfileOperationCompleted, userState);
        }
        
        private void OnDeletedatingProfileOperationCompleted(object arg) {
            if ((this.DeletedatingProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletedatingProfileCompleted(this, new DeletedatingProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RunAndFindMatches", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public List<MatchedResults> RunAndFindMatches(Profile profile, DatingProfile dprofile) {
            object[] results = this.Invoke("RunAndFindMatches", new object[] {
                        profile,
                        dprofile});
            return ((List<MatchedResults>)(results[0]));
        }
        
        /// <remarks/>
        public void RunAndFindMatchesAsync(Profile profile, DatingProfile dprofile) {
            this.RunAndFindMatchesAsync(profile, dprofile, null);
        }
        
        /// <remarks/>
        public void RunAndFindMatchesAsync(Profile profile, DatingProfile dprofile, object userState) {
            if ((this.RunAndFindMatchesOperationCompleted == null)) {
                this.RunAndFindMatchesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRunAndFindMatchesOperationCompleted);
            }
            this.InvokeAsync("RunAndFindMatches", new object[] {
                        profile,
                        dprofile}, this.RunAndFindMatchesOperationCompleted, userState);
        }
        
        private void OnRunAndFindMatchesOperationCompleted(object arg) {
            if ((this.RunAndFindMatchesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RunAndFindMatchesCompleted(this, new RunAndFindMatchesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EndSession", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EndSession(Profile profile) {
            object[] results = this.Invoke("EndSession", new object[] {
                        profile});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EndSessionAsync(Profile profile) {
            this.EndSessionAsync(profile, null);
        }
        
        /// <remarks/>
        public void EndSessionAsync(Profile profile, object userState) {
            if ((this.EndSessionOperationCompleted == null)) {
                this.EndSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEndSessionOperationCompleted);
            }
            this.InvokeAsync("EndSession", new object[] {
                        profile}, this.EndSessionOperationCompleted, userState);
        }
        
        private void OnEndSessionOperationCompleted(object arg) {
            if ((this.EndSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EndSessionCompleted(this, new EndSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNumberOfActiveUsers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetNumberOfActiveUsers() {
            object[] results = this.Invoke("GetNumberOfActiveUsers", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetNumberOfActiveUsersAsync() {
            this.GetNumberOfActiveUsersAsync(null);
        }
        
        /// <remarks/>
        public void GetNumberOfActiveUsersAsync(object userState) {
            if ((this.GetNumberOfActiveUsersOperationCompleted == null)) {
                this.GetNumberOfActiveUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNumberOfActiveUsersOperationCompleted);
            }
            this.InvokeAsync("GetNumberOfActiveUsers", new object[0], this.GetNumberOfActiveUsersOperationCompleted, userState);
        }
        
        private void OnGetNumberOfActiveUsersOperationCompleted(object arg) {
            if ((this.GetNumberOfActiveUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNumberOfActiveUsersCompleted(this, new GetNumberOfActiveUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    //public partial class Profile {
        
    //    private string nickNameField;
        
    //    private string passwordField;
        
    //    private string firstNameField;
        
    //    private string lastNameField;
        
    //    private string sexField;
        
    //    private string hairField;
        
    //    private string raceField;
        
    //    private string interestField;
        
    //    private int ageField;
        
    //    private int onlineField;
        
    //    private int heightField;
        
    //    private int weightField;
        
    //    private int phoneField;
        
    //    private double longitudeField;
        
    //    private double latitudeField;
        
    //    private double distanceField;
        
    //    /// <remarks/>
    //    public string NickName {
    //        get {
    //            return this.nickNameField;
    //        }
    //        set {
    //            this.nickNameField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Password {
    //        get {
    //            return this.passwordField;
    //        }
    //        set {
    //            this.passwordField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string FirstName {
    //        get {
    //            return this.firstNameField;
    //        }
    //        set {
    //            this.firstNameField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string LastName {
    //        get {
    //            return this.lastNameField;
    //        }
    //        set {
    //            this.lastNameField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Sex {
    //        get {
    //            return this.sexField;
    //        }
    //        set {
    //            this.sexField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Hair {
    //        get {
    //            return this.hairField;
    //        }
    //        set {
    //            this.hairField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Race {
    //        get {
    //            return this.raceField;
    //        }
    //        set {
    //            this.raceField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Interest {
    //        get {
    //            return this.interestField;
    //        }
    //        set {
    //            this.interestField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Age {
    //        get {
    //            return this.ageField;
    //        }
    //        set {
    //            this.ageField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Online {
    //        get {
    //            return this.onlineField;
    //        }
    //        set {
    //            this.onlineField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Height {
    //        get {
    //            return this.heightField;
    //        }
    //        set {
    //            this.heightField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Weight {
    //        get {
    //            return this.weightField;
    //        }
    //        set {
    //            this.weightField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Phone {
    //        get {
    //            return this.phoneField;
    //        }
    //        set {
    //            this.phoneField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public double Longitude {
    //        get {
    //            return this.longitudeField;
    //        }
    //        set {
    //            this.longitudeField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public double Latitude {
    //        get {
    //            return this.latitudeField;
    //        }
    //        set {
    //            this.latitudeField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public double Distance {
    //        get {
    //            return this.distanceField;
    //        }
    //        set {
    //            this.distanceField = value;
    //        }
    //    }
    //}
    
    /// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    //public partial class MatchedResults {
        
    //    private int phoneField;
        
    //    private string nameField;
        
    //    private double matchPercentageField;
        
    //    /// <remarks/>
    //    public int Phone {
    //        get {
    //            return this.phoneField;
    //        }
    //        set {
    //            this.phoneField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Name {
    //        get {
    //            return this.nameField;
    //        }
    //        set {
    //            this.nameField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public double MatchPercentage {
    //        get {
    //            return this.matchPercentageField;
    //        }
    //        set {
    //            this.matchPercentageField = value;
    //        }
    //    }
    //}
    
    /// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    //public partial class DatingProfile {
        
    //    private string hairField;
        
    //    private int max_WeightField;
        
    //    private int min_WeightField;
        
    //    private string raceField;
        
    //    private int min_AgeField;
        
    //    private int max_AgeField;
        
    //    private string nickNameField;
        
    //    private string sexField;
        
    //    private int height_MaxField;
        
    //    private int height_MinField;
        
    //    private string interestField;
        
    //    private int rangeField;
        
    //    /// <remarks/>
    //    public string Hair {
    //        get {
    //            return this.hairField;
    //        }
    //        set {
    //            this.hairField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Max_Weight {
    //        get {
    //            return this.max_WeightField;
    //        }
    //        set {
    //            this.max_WeightField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Min_Weight {
    //        get {
    //            return this.min_WeightField;
    //        }
    //        set {
    //            this.min_WeightField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Race {
    //        get {
    //            return this.raceField;
    //        }
    //        set {
    //            this.raceField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Min_Age {
    //        get {
    //            return this.min_AgeField;
    //        }
    //        set {
    //            this.min_AgeField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Max_Age {
    //        get {
    //            return this.max_AgeField;
    //        }
    //        set {
    //            this.max_AgeField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string NickName {
    //        get {
    //            return this.nickNameField;
    //        }
    //        set {
    //            this.nickNameField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Sex {
    //        get {
    //            return this.sexField;
    //        }
    //        set {
    //            this.sexField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Height_Max {
    //        get {
    //            return this.height_MaxField;
    //        }
    //        set {
    //            this.height_MaxField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Height_Min {
    //        get {
    //            return this.height_MinField;
    //        }
    //        set {
    //            this.height_MinField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Interest {
    //        get {
    //            return this.interestField;
    //        }
    //        set {
    //            this.interestField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Range {
    //        get {
    //            return this.rangeField;
    //        }
    //        set {
    //            this.rangeField = value;
    //        }
    //    }
    //}
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void UpdateProfileCompletedEventHandler(object sender, UpdateProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void UpdateDatingProfileCompletedEventHandler(object sender, UpdateDatingProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateDatingProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateDatingProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void InsertNewUserCompletedEventHandler(object sender, InsertNewUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertNewUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertNewUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetUserProfileCompletedEventHandler(object sender, GetUserProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Profile Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Profile)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void LoginCheckCompletedEventHandler(object sender, LoginCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void LoadDatingProfileCompletedEventHandler(object sender, LoadDatingProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadDatingProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadDatingProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void DeletedatingProfileCompletedEventHandler(object sender, DeletedatingProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeletedatingProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeletedatingProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void RunAndFindMatchesCompletedEventHandler(object sender, RunAndFindMatchesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RunAndFindMatchesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RunAndFindMatchesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MatchedResults[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MatchedResults[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void EndSessionCompletedEventHandler(object sender, EndSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EndSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EndSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetNumberOfActiveUsersCompletedEventHandler(object sender, GetNumberOfActiveUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNumberOfActiveUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNumberOfActiveUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591