//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4927.
// 
#pragma warning disable 1591

namespace NoIdeas.Client.cloudWebRef {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    using NoIdeas.Phone.Lib;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NoIdeasWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class NoIdeasWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UpdateProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindMatchesOperationCompleted;
        
        private System.Threading.SendOrPostCallback EndSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNumberOfActiveUsersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NoIdeasWebService() {
            this.Url = global::NoIdeas.Client.Properties.Settings.Default.NoIdeas_Client_cloudWebRef_NoIdeasWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UpdateProfileCompletedEventHandler UpdateProfileCompleted;
        
        /// <remarks/>
        public event FindMatchesCompletedEventHandler FindMatchesCompleted;
        
        /// <remarks/>
        public event EndSessionCompletedEventHandler EndSessionCompleted;
        
        /// <remarks/>
        public event GetNumberOfActiveUsersCompletedEventHandler GetNumberOfActiveUsersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateProfile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateProfile(Profile profile) {
            object[] results = this.Invoke("UpdateProfile", new object[] {
                        profile});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateProfileAsync(Profile profile) {
            this.UpdateProfileAsync(profile, null);
        }
        
        /// <remarks/>
        public void UpdateProfileAsync(Profile profile, object userState) {
            if ((this.UpdateProfileOperationCompleted == null)) {
                this.UpdateProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateProfileOperationCompleted);
            }
            this.InvokeAsync("UpdateProfile", new object[] {
                        profile}, this.UpdateProfileOperationCompleted, userState);
        }
        
        private void OnUpdateProfileOperationCompleted(object arg) {
            if ((this.UpdateProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateProfileCompleted(this, new UpdateProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindMatches", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable FindMatches(double longitude, double latitude) {
            object[] results = this.Invoke("FindMatches", new object[] {
                        longitude,
                        latitude});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void FindMatchesAsync(double longitude, double latitude) {
            this.FindMatchesAsync(longitude, latitude, null);
        }
        
        /// <remarks/>
        public void FindMatchesAsync(double longitude, double latitude, object userState) {
            if ((this.FindMatchesOperationCompleted == null)) {
                this.FindMatchesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindMatchesOperationCompleted);
            }
            this.InvokeAsync("FindMatches", new object[] {
                        longitude,
                        latitude}, this.FindMatchesOperationCompleted, userState);
        }
        
        private void OnFindMatchesOperationCompleted(object arg) {
            if ((this.FindMatchesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindMatchesCompleted(this, new FindMatchesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EndSession", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EndSession(Profile profile) {
            object[] results = this.Invoke("EndSession", new object[] {
                        profile});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EndSessionAsync(Profile profile) {
            this.EndSessionAsync(profile, null);
        }
        
        /// <remarks/>
        public void EndSessionAsync(Profile profile, object userState) {
            if ((this.EndSessionOperationCompleted == null)) {
                this.EndSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEndSessionOperationCompleted);
            }
            this.InvokeAsync("EndSession", new object[] {
                        profile}, this.EndSessionOperationCompleted, userState);
        }
        
        private void OnEndSessionOperationCompleted(object arg) {
            if ((this.EndSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EndSessionCompleted(this, new EndSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNumberOfActiveUsers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetNumberOfActiveUsers() {
            object[] results = this.Invoke("GetNumberOfActiveUsers", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetNumberOfActiveUsersAsync() {
            this.GetNumberOfActiveUsersAsync(null);
        }
        
        /// <remarks/>
        public void GetNumberOfActiveUsersAsync(object userState) {
            if ((this.GetNumberOfActiveUsersOperationCompleted == null)) {
                this.GetNumberOfActiveUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNumberOfActiveUsersOperationCompleted);
            }
            this.InvokeAsync("GetNumberOfActiveUsers", new object[0], this.GetNumberOfActiveUsersOperationCompleted, userState);
        }
        
        private void OnGetNumberOfActiveUsersOperationCompleted(object arg) {
            if ((this.GetNumberOfActiveUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNumberOfActiveUsersCompleted(this, new GetNumberOfActiveUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    //public partial class Profile {
        
    //    private double longitudeField;
        
    //    private double latitudeField;
        
    //    private double distanceField;
        
    //    private int interest3Field;
        
    //    private int interest2Field;
        
    //    private int interest1Field;
        
    //    private int hairField;
        
    //    private int weightField;
        
    //    private int height_inField;
        
    //    private int height_ftField;
        
    //    private int raceField;
        
    //    private int onlineField;
        
    //    private string nameField;
        
    //    private string lastNameField;
        
    //    private int ageField;
        
    //    private string nickNameField;
        
    //    private string sexField;
        
    //    /// <remarks/>
    //    public double Longitude {
    //        get {
    //            return this.longitudeField;
    //        }
    //        set {
    //            this.longitudeField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public double Latitude {
    //        get {
    //            return this.latitudeField;
    //        }
    //        set {
    //            this.latitudeField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public double Distance {
    //        get {
    //            return this.distanceField;
    //        }
    //        set {
    //            this.distanceField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Interest3 {
    //        get {
    //            return this.interest3Field;
    //        }
    //        set {
    //            this.interest3Field = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Interest2 {
    //        get {
    //            return this.interest2Field;
    //        }
    //        set {
    //            this.interest2Field = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Interest1 {
    //        get {
    //            return this.interest1Field;
    //        }
    //        set {
    //            this.interest1Field = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Hair {
    //        get {
    //            return this.hairField;
    //        }
    //        set {
    //            this.hairField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Weight {
    //        get {
    //            return this.weightField;
    //        }
    //        set {
    //            this.weightField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Height_in {
    //        get {
    //            return this.height_inField;
    //        }
    //        set {
    //            this.height_inField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Height_ft {
    //        get {
    //            return this.height_ftField;
    //        }
    //        set {
    //            this.height_ftField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Race {
    //        get {
    //            return this.raceField;
    //        }
    //        set {
    //            this.raceField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Online {
    //        get {
    //            return this.onlineField;
    //        }
    //        set {
    //            this.onlineField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Name {
    //        get {
    //            return this.nameField;
    //        }
    //        set {
    //            this.nameField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string LastName {
    //        get {
    //            return this.lastNameField;
    //        }
    //        set {
    //            this.lastNameField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Age {
    //        get {
    //            return this.ageField;
    //        }
    //        set {
    //            this.ageField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string NickName {
    //        get {
    //            return this.nickNameField;
    //        }
    //        set {
    //            this.nickNameField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Sex {
    //        get {
    //            return this.sexField;
    //        }
    //        set {
    //            this.sexField = value;
    //        }
    //    }
    //}
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void UpdateProfileCompletedEventHandler(object sender, UpdateProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void FindMatchesCompletedEventHandler(object sender, FindMatchesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindMatchesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindMatchesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void EndSessionCompletedEventHandler(object sender, EndSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EndSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EndSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetNumberOfActiveUsersCompletedEventHandler(object sender, GetNumberOfActiveUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNumberOfActiveUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNumberOfActiveUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591