//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.4927.
// 
namespace MainProject.cloudWebRef {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using NoIdeas.Phone.Lib;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NoIdeasWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class NoIdeasWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public NoIdeasWebService() {
            this.Url = "http://noideaswebservice.cloudapp.net/NoIdeasWebService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateProfile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateProfile(Profile profile) {
            object[] results = this.Invoke("UpdateProfile", new object[] {
                        profile});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateProfile(Profile profile, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateProfile", new object[] {
                        profile}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndUpdateProfile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateDatingProfile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateDatingProfile(DatingProfile dprofile) {
            object[] results = this.Invoke("UpdateDatingProfile", new object[] {
                        dprofile});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateDatingProfile(DatingProfile dprofile, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateDatingProfile", new object[] {
                        dprofile}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndUpdateDatingProfile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertNewUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertNewUser(Profile profile) {
            object[] results = this.Invoke("InsertNewUser", new object[] {
                        profile});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertNewUser(Profile profile, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertNewUser", new object[] {
                        profile}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndInsertNewUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserProfile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Profile GetUserProfile(string nickName) {
            object[] results = this.Invoke("GetUserProfile", new object[] {
                        nickName});
            return ((Profile)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUserProfile(string nickName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUserProfile", new object[] {
                        nickName}, callback, asyncState);
        }
        
        /// <remarks/>
        public Profile EndGetUserProfile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Profile)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoginCheck", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool LoginCheck(string nickName, string password) {
            object[] results = this.Invoke("LoginCheck", new object[] {
                        nickName,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLoginCheck(string nickName, string password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LoginCheck", new object[] {
                        nickName,
                        password}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndLoginCheck(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadDatingProfile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool LoadDatingProfile(DatingProfile dprofile) {
            object[] results = this.Invoke("LoadDatingProfile", new object[] {
                        dprofile});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLoadDatingProfile(DatingProfile dprofile, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LoadDatingProfile", new object[] {
                        dprofile}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndLoadDatingProfile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeletedatingProfile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeletedatingProfile(DatingProfile dprofile) {
            object[] results = this.Invoke("DeletedatingProfile", new object[] {
                        dprofile});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeletedatingProfile(DatingProfile dprofile, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DeletedatingProfile", new object[] {
                        dprofile}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndDeletedatingProfile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindMatches", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MatchedResults[] FindMatches(string username, double longitude, double latitude) {
            object[] results = this.Invoke("FindMatches", new object[] {
                        username,
                        longitude,
                        latitude});
            return ((MatchedResults[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFindMatches(string username, double longitude, double latitude, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FindMatches", new object[] {
                        username,
                        longitude,
                        latitude}, callback, asyncState);
        }
        
        /// <remarks/>
        public MatchedResults[] EndFindMatches(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MatchedResults[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EndSession", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EndSession(Profile profile) {
            object[] results = this.Invoke("EndSession", new object[] {
                        profile});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEndSession(Profile profile, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EndSession", new object[] {
                        profile}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndEndSession(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNumberOfActiveUsers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetNumberOfActiveUsers() {
            object[] results = this.Invoke("GetNumberOfActiveUsers", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetNumberOfActiveUsers(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetNumberOfActiveUsers", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public int EndGetNumberOfActiveUsers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
    }
    
    /// <remarks/>
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    //public partial class Profile {
        
    //    private string nickNameField;
        
    //    private string passwordField;
        
    //    private string firstNameField;
        
    //    private string lastNameField;
        
    //    private string sexField;
        
    //    private string hairField;
        
    //    private string raceField;
        
    //    private string interestField;
        
    //    private int ageField;
        
    //    private int onlineField;
        
    //    private int heightField;
        
    //    private int weightField;
        
    //    private int phoneField;
        
    //    private double longitudeField;
        
    //    private double latitudeField;
        
    //    private double distanceField;
        
    //    /// <remarks/>
    //    public string NickName {
    //        get {
    //            return this.nickNameField;
    //        }
    //        set {
    //            this.nickNameField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Password {
    //        get {
    //            return this.passwordField;
    //        }
    //        set {
    //            this.passwordField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string FirstName {
    //        get {
    //            return this.firstNameField;
    //        }
    //        set {
    //            this.firstNameField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string LastName {
    //        get {
    //            return this.lastNameField;
    //        }
    //        set {
    //            this.lastNameField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Sex {
    //        get {
    //            return this.sexField;
    //        }
    //        set {
    //            this.sexField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Hair {
    //        get {
    //            return this.hairField;
    //        }
    //        set {
    //            this.hairField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Race {
    //        get {
    //            return this.raceField;
    //        }
    //        set {
    //            this.raceField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Interest {
    //        get {
    //            return this.interestField;
    //        }
    //        set {
    //            this.interestField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Age {
    //        get {
    //            return this.ageField;
    //        }
    //        set {
    //            this.ageField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Online {
    //        get {
    //            return this.onlineField;
    //        }
    //        set {
    //            this.onlineField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Height {
    //        get {
    //            return this.heightField;
    //        }
    //        set {
    //            this.heightField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Weight {
    //        get {
    //            return this.weightField;
    //        }
    //        set {
    //            this.weightField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Phone {
    //        get {
    //            return this.phoneField;
    //        }
    //        set {
    //            this.phoneField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public double Longitude {
    //        get {
    //            return this.longitudeField;
    //        }
    //        set {
    //            this.longitudeField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public double Latitude {
    //        get {
    //            return this.latitudeField;
    //        }
    //        set {
    //            this.latitudeField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public double Distance {
    //        get {
    //            return this.distanceField;
    //        }
    //        set {
    //            this.distanceField = value;
    //        }
    //    }
    //}
    
    ///// <remarks/>
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    //public partial class MatchedResults {
        
    //    private int phoneField;
        
    //    private string nameField;
        
    //    private double matchPercentageField;
        
    //    /// <remarks/>
    //    public int Phone {
    //        get {
    //            return this.phoneField;
    //        }
    //        set {
    //            this.phoneField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Name {
    //        get {
    //            return this.nameField;
    //        }
    //        set {
    //            this.nameField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public double MatchPercentage {
    //        get {
    //            return this.matchPercentageField;
    //        }
    //        set {
    //            this.matchPercentageField = value;
    //        }
    //    }
    //}
    
    ///// <remarks/>
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    //public partial class DatingProfile {
        
    //    private string hairField;
        
    //    private int max_WeightField;
        
    //    private int min_WeightField;
        
    //    private string raceField;
        
    //    private int min_AgeField;
        
    //    private int max_AgeField;
        
    //    private string nickNameField;
        
    //    private string sexField;
        
    //    private int height_MaxField;
        
    //    private int height_MinField;
        
    //    private string interestField;
        
    //    private int rangeField;
        
    //    /// <remarks/>
    //    public string Hair {
    //        get {
    //            return this.hairField;
    //        }
    //        set {
    //            this.hairField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Max_Weight {
    //        get {
    //            return this.max_WeightField;
    //        }
    //        set {
    //            this.max_WeightField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Min_Weight {
    //        get {
    //            return this.min_WeightField;
    //        }
    //        set {
    //            this.min_WeightField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Race {
    //        get {
    //            return this.raceField;
    //        }
    //        set {
    //            this.raceField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Min_Age {
    //        get {
    //            return this.min_AgeField;
    //        }
    //        set {
    //            this.min_AgeField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Max_Age {
    //        get {
    //            return this.max_AgeField;
    //        }
    //        set {
    //            this.max_AgeField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string NickName {
    //        get {
    //            return this.nickNameField;
    //        }
    //        set {
    //            this.nickNameField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Sex {
    //        get {
    //            return this.sexField;
    //        }
    //        set {
    //            this.sexField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Height_Max {
    //        get {
    //            return this.height_MaxField;
    //        }
    //        set {
    //            this.height_MaxField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Height_Min {
    //        get {
    //            return this.height_MinField;
    //        }
    //        set {
    //            this.height_MinField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public string Interest {
    //        get {
    //            return this.interestField;
    //        }
    //        set {
    //            this.interestField = value;
    //        }
    //    }
        
    //    /// <remarks/>
    //    public int Range {
    //        get {
    //            return this.rangeField;
    //        }
    //        set {
    //            this.rangeField = value;
    //        }
    //    }
    //}
}
